// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BatteryCapacity - return EV Battery Capacity reading
type BatteryCapacity struct {
	// The total capacity of the vehicle's battery (in kilowatt-hours).
	Capacity *float32 `json:"capacity,omitempty"`
}
