// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ChargeActionActionEnum string

const (
	ChargeActionActionEnumStart ChargeActionActionEnum = "START"
	ChargeActionActionEnumStop  ChargeActionActionEnum = "STOP"
)

func (e ChargeActionActionEnum) ToPointer() *ChargeActionActionEnum {
	return &e
}

func (e *ChargeActionActionEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "START":
		fallthrough
	case "STOP":
		*e = ChargeActionActionEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChargeActionActionEnum: %v", v)
	}
}

type ChargeAction struct {
	Action *ChargeActionActionEnum `json:"action,omitempty"`
}
