// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SecurityResponseStatusEnum string

const (
	SecurityResponseStatusEnumSuccess SecurityResponseStatusEnum = "SUCCESS"
	SecurityResponseStatusEnumFailed  SecurityResponseStatusEnum = "FAILED"
)

func (e SecurityResponseStatusEnum) ToPointer() *SecurityResponseStatusEnum {
	return &e
}

func (e *SecurityResponseStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "SUCCESS":
		fallthrough
	case "FAILED":
		*e = SecurityResponseStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for SecurityResponseStatusEnum: %s", s)
	}
}

// SecurityResponse - return Compatibility
type SecurityResponse struct {
	Message *string                     `json:"message,omitempty"`
	Status  *SecurityResponseStatusEnum `json:"status,omitempty"`
}
